### ISSUE TITLE
Generate link which uses the "craft all" options

### ISSUE THREAD

**Issue by nicodemus4802** [gw2efficiency/issues#1125]
It would be nice if the link to share a crafting calculation could include a result with the "craft all" function already enabled. This would make it easier to decipher which item to make when crafting for Faction Provisioners without having to select the option after loading the page.

Just a small QoL upgrade...

**Comment by queicherius** [comment]
I am opposed to adding that option because the user's expectation on gw2e generally is that whatever they do, the most efficient option(s) are always immediately visible and at the top.

With links like that (especially looking at sharing) it would default to a suboptimal method of crafting, and it would not be immediately obvious to the user (especially new players, which use the shared links a lot of times).
