### ISSUE TITLE
Update set 2 legendary crafting for HoT vs PoF options

### ISSUE THREAD

**Issue by valoralash** [gw2efficiency/issues#1169]
The crafting calculator currently only seems to support HoT-type recipes.  Unless I am completely off base (and going to be sorrily disappointed) there is a PoF-type crafting track for the legendary weapons released post-PoF.
The wiki does seem to default to the HoT recipes as well, FYI.
Thanks for considering!

**Comment by queicherius** [comment]
The calculator only supports a single recipe (the cheapest one). Since both of them are the same price, the "first one in the list" always gets picked. However, you can just make the recipe yourself via the multi-recipe feature.

https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-81812;1-82003;1-71820;1-86036
