### ISSUE TITLE
Many items are incorrectly marked as not sold or crafted

### ISSUE THREAD

**Issue by robbob4** [gw2efficiency/issues#1174]
- [x] Legendary War Insight is marked incorrectly as NOT SOLD OR CRAFTED when it is sold by two vendors for 1095 skirmish tickets.
- [x] Cube of Stabilized Dark Energy is marked incorrectly as NOT SOLD OR CRAFTED when it is crafted using 1 Ball of Dark Energy and 75 Stabilizing Matrices.
- [x] Certificate of Honor is marked incorrectly as NOT SOLD OR CRAFTED when it is sold by two vendors for 500 badges of honor.
- [x] Certificate of Heroics is marked incorrectly as NOT SOLD OR CRAFTED when it is sold by four vendors for either 250 proofs of heroics or 250 testimonies of heroics.
- [x] Glob of Condensed Spirit Energy is marked incorrectly as NOT SOLD OR CRAFTED when it is sold by four vendors for 100 spirit shards.

**Comment by queicherius** [comment]
This information is not available in the API, and as such would have to be added manually by us for all available 60.000 items. This is something we *might* want to do in the future (see #933, #1069) but for now this is the intended behaviour :)

That said, I'll keep this ticket open, to add these manually, since they are fairly big ticket items (we already have a list of those where I can append them)

**Comment by queicherius** [comment]
+ https://wiki.guildwars2.com/wiki/Pile_of_Powdered_Gelatin_Mix

**Comment by queicherius** [comment]
Now live.
