### ISSUE TITLE
Player Statistics Suggestion: Accounts played within a timeframe.

### ISSUE THREAD

**Issue by rediche** [gw2efficiency/issues#1198]
With GW2E having such a big sample size, I think it would be interesting to see some kind of statistic of how much people play GW2 within some timeframes.

I'm thinking something along the lines of:

- Players who played at least 1 hour within the last 24 hours, 7 days and 30 days.
- Total playtime of all accounts on GW2E within the last 24 hours, 7 days and 30 days.

This would a super interesting statistic. If possible, it would also be cool to see it spread out for both EU and NA to track activity levels across them.

It would also be super interesting, if this could be tracked over time.

**Comment by queicherius** [comment]
Technically we already have the data to do this, since we keep the "playtime" statistic for all accounts, so it would just be a case of generating it from that. Not sure how much effort the generation would be, but it sounds reasonable-ish.

However, I am not sure if this is a feature I want to add. I agree that it would be cool and interesting, but my fear is that it will be used for uninformed opinion posts about "the game is dying" / "the game is super alive".

**Comment by queicherius** [comment]
Closing this in favour of #653, which might add less fear and produce more interesting statistics.
