### ISSUE TITLE
Missing/Updated mini Values

### ISSUE THREAD

**Issue by DerpyDerpMCDerpicus** [gw2efficiency/issues#1199]
Missing values:

**Mini Blue Siege Golem** - 10g (+25 Guild Commendations) - Vendor
**Mini Red Siege Golem** - 10g (+25 Guild Commendations) - Vendor
**Mini Green Siege Golem** - 10g (+25 Guild Commendations) - Vendor

**Mini First Mate Horrik** - 200gems - Season 1 Memory Box-Flame and Festivals

**Mini Dolyak** - 250 Memory of Battle (+260 Skirmish Tickets) - Vendor

**Mini Mordrem Troll** - 50s (+1200 Bandit Crests) - Vendor
**Mini Mordrem Husk** - 50s (+1200 Bandit Crests) - Vendor
**Mini Blademaster Diarmid** - 1g (+250 Crystalline Ore) - Vendor
**Mini Exalted Sage** - 5g (+1000 Aurillium) - Vendor
**Mini Nuhoch** - 5g (+1000 Ley-Line Crystal) - Vendor

**Mini Ghostly Justiciar Hablion** - 1g (+2500 Unbound Magic) - Vendor
**Mini Jade Construct** - 1g50s (+3750 Unbound Magic) - Vendor
**Mini Bloodstone Elemental** - 1g (+2500 Unbound Magic) - Vendor

**Mini Dragon Gourdon** - 10 Jorbreaker - Vendor
**Mini Trailblazer Roller Beetle** - 400gems - Gemstore

Update - due to new methodes of acquiring and the previous way of obtaining has been discontinued.

**Mini Helmed Moa Racer** - 25 Jorbreaker - Vendor (TP verion is discontinued, currently 30 on TP)

_Season 1 Memory Box-Flame and Festivals_ - 200gems
**Mini Holographic Branded Minotaur** - old was a 500 gem box (discontinued) shared 2 others
**Mini Holographic Axe-Wielding Destroyer** - old was a 500 gem box (discontinued) shared 2 others
**Mini Holographic Corrupted Wolf** - old was a 500 gem box (discontinued) shared 2 others
**Mini Holographic Colossus** - old was a Mystic Forge recipe with the 4 other holographic dragon minions, still available, but mostly unused. The recipe currently is 600gems + Mini Holographic Risen Knight, current value on gw2eff is 500gems
**Mini Molten Firestorm** - TP version is discontinued, currently 20 on TP

_Season 1 Memory Box—Scarlet vs. Lion's Arch_ - 200gems
**Mini Molten Berserker** - old was a 500 gem box (discontinued) shared with 2 others
**Mini Toxic Warlock** - old was a 500 gem box (discontinued) shared with 2 others
**Mini Aetherblade Admiral** - old was a 500 gem box (discontinued) shared with 2 others
**Mini Twisted Watchwork Moa** - TP version is discontinued, currently 111 on TP
**Mini Armored Scarlet Briar** - old was a Mystic Forge recipe with 4 other minis, still available, but mostly unused. The recipe currently is 600gems + Mini Mai Trin, current value on gw2eff is 500gems

**Comment by queicherius** [comment]
@sutgon You added a whole bunch of those, are there still any left in the list?

**Comment by sutgon** [comment]
From this list:
 * Mini Ghostly Justiciar Hablion
 * Mini Trailblazer Roller Beetle
   *  But would adding the value make sense as the only time it has been available you could just get it for free? Would add it once it gets reintroduced.
 * Mini First Mate Horrik
   * Currently at no value, and there is no one set price to get it for, would giving it the price of one S1 Flame and Festivals box make sense?
 * All the outlined S1 memory box items.
 
For Horrik and other S1 memory box minis, there are multiple ways to approach this.

Could prolly keep Twisted Watchwork Moa at the TP price (for now), maybe Firestorm as well as the other options are RNG and really unpleasant containers to drop research due to the cost. 

The holographics could be also valued by the Dragon Bash containers, for that some drop data exists, that valuation would probably be fairer than valuing them by S1 gemstore containers. 

For the Scarlet VS LA the only (new) option would be to value by the container drop research, which again, is rather unpleasant to gather.

Or another option would just be valuing them at 200 gems, the price of the container..


For any kind of drop research based valuation though there is the question of how to exactly get a valuation for an item based on that as you aren't quite rolling for just the item, you're also getting "byproducts" that are worth something.

**Comment by queicherius** [comment]
> Mini Ghostly Justiciar Hablion

Since it's only 1g, I'd say this is not a priority.

> Mini Trailblazer Roller Beetle - But would adding the value make sense as the only time it has been available you could just get it for free? Would add it once it gets reintroduced.

👍 for ignoring it

> Mini First Mate Horrik + All the outlined S1 memory box items.
> Could prolly keep Twisted Watchwork Moa at the TP price (for now), maybe Firestorm as well as the other options are RNG and really unpleasant containers to drop research due to the cost.
> Or another option would just be valuing them at 200 gems, the price of the container..

I think keep the TP-able items at TP price, and give the other ones the 200 gems price, since that is how we also handle the items that are random from BLTC atm (= 1 key).

@sutgon Would you be up for updating this?

**Comment by queicherius** [comment]
Should be updated by now, feel free to update another one if stuff is still missing.
