### ISSUE TITLE
Update miniatures to reference custom unlock_items

### ISSUE THREAD

**Issue by DerpyDerpMCDerpicus** [gw2efficiency/issues#1200]
Mini Spooky Mounts Pack - Black Lion Exclusives Chest - TP
Mini Spooky Raptor 
Mini Spooky Skimmer 
Mini Spooky Springer
Mini Spooky Jackal
Mini Spooky Griffon 

Mini Kormeerkat - 350gems - Gemstore

Mini Cozy Wintersday Mounts Pack - Black Lion Exclusives Chest - TP
Mini Cozy Wintersday Raptor
Mini Cozy Wintersday Skimmer
Mini Cozy Wintersday Springer
Mini Cozy Wintersday Jackal
Mini Cozy Wintersday Griffon

Mini Summit Wildhorn Springer - 25 Black Lion Statuette
Mini Umbral Demon Skimmer - 25 Black Lion Statuette
Mini Resplendent Avialan Raptor - 25 Black Lion Statuette
Mini Reforged Warhound Jackal - 25 Black Lion Statuette
Mini Grand Lion Griffon	Miniature - 25 Black Lion Statuette

Mini Lucky Lantern Puppy - 400gems - Gemstore

Mini Branded Mounts Pack - Black Lion Exclusives Chest - TP
Mini Branded Raptor 
Mini Branded Skimmer 
Mini Branded Springer
Mini Branded Jackal
Mini Branded Griffon 

Mini Awakened Mounts Pack - Black Lion Exclusives Chest - TP
Mini Awakened Raptor 
Mini Awakened Skimmer 
Mini Awakened Springer
Mini Awakened Jackal
Mini Awakened Griffon 

Mini Exo-Suit Mounts Pack - 60 Black Lion Statuette
Mini Exo-Suit Raptor 
Mini Exo-Suit Skimmer 
Mini Exo-Suit Springer
Mini Exo-Suit Jackal
Mini Exo-Suit Griffon 

Mini Shrine Guardian - 400gems - Gemstore

**Comment by queicherius** [comment]
@sutgon You added a whole bunch of those, are there still any left in the list?

**Comment by sutgon** [comment]
The statuette minis could be perhaps added to item inheritance for their cost in statuettes, otherwise all of the packs and kormeekat/puppy/guardian prices are in the static data files, but the reason the values aren't reflected is due to /minis endpoint not referencing unlock item IDs.
Perhaps yet another static data thing for mapping ids in /minis to ids in /items as it has been quite a while the API has had this "bug"? Ideally something to also overwrite the names as in api they're all ((208738)). Duno if it has been proposed or considered before.

**Comment by queicherius** [comment]
Yeah, that sounds like something we should do at this point... :/ There is a few annoyances with that, e.g. multiple languages. Technically if we correctly overwrite the `unlock_items` we could read the names from the items themselves.

**Comment by queicherius** [comment]
I kinda wanna hold back on overwriting unlock items for now, since maintaining just the ones we currently have is already a bit of a hassle, so I added this to the backburner
