### ISSUE TITLE
Invalid skin value

### ISSUE THREAD

**Issue by malagus** [gw2efficiency/issues#1215]
Many skins don't have value but corresponding item have.
Examples:
![obraz](https://user-images.githubusercontent.com/12558492/64908076-9d8e6100-d6fb-11e9-9450-92df7b31f90d.png)
![obraz](https://user-images.githubusercontent.com/12558492/64908081-a97a2300-d6fb-11e9-81eb-7a96d66e591c.png)
![obraz](https://user-images.githubusercontent.com/12558492/64908116-fe1d9e00-d6fb-11e9-8585-38b40102ee17.png)
![obraz](https://user-images.githubusercontent.com/12558492/64908118-04ac1580-d6fc-11e9-974b-488300cb6e45.png)

**Comment by queicherius** [comment]
Thank you very much for the report!

I debugged this and found that if a skin either a) gets flagged as overinflated (using the buy price instead of the sell price) or b) there are no sell orders AND there is only one way to get the skin, the value of the skin gets completely ignored. This will be fixed with the next release.

**Comment by queicherius** [comment]
Fixed in today's release. Will probably take a while to update all the skins, but should be done in a day or so.

**Comment by queicherius** [comment]
It looks like this is still broken, even tho for all intents and purposes in the code it should be fixed. Will need a little more debugging. :/

**Comment by queicherius** [comment]
The first 2 got fixed, the ascended ones don't count because `valueIsVendor` is not set correctly.
