### ISSUE TITLE
Move Show Delta out of the chart and scale value over

### ISSUE THREAD

**Issue by JoniMega** [gw2efficiency/issues#1310]
There are two problems with the current layout. The "show Delta" select button can overlap the chart and the scale value being overlapped by the chart.

It would be minor enhancement/fix if you can move out the "Show Delta" or you can make that the bar never goes over. 
Scale value maybe it would be better if is over the chart, but I'm not sure.

![image](https://user-images.githubusercontent.com/12009707/82157965-0595d800-9885-11ea-9793-50cb9e31708b.png)

**Comment by queicherius** [comment]
I kindof liked the "Show Delta" being contained within the chart, but I am not sure I want to give up the scaling for that. I'll keep it in mind once I work on the pages with charts more (this was just the first step to make a migration to new code possible).

As for the labels behind the values, that was an intentional decision from me, because especially for the account value graph (which is what most people see 90% of the time) it looked pretty bad with the labels being on top of the graph.

**Comment by queicherius** [comment]
Decided to keep the show delta as is, so we are using more screen real estate in exchange for occasional clipping

**Comment by queicherius** [comment]
Reopening because we are showing more information there with #1320 so it makes sense

**Comment by queicherius** [comment]
This is now live.
