### ISSUE TITLE
Player Statistic suggestion: How many of each legendary

### ISSUE THREAD

**Issue by rediche** [gw2efficiency/issues#1331]
Basically a list of every legendary in the game and how many are in circulation based on the accounts that are being scraped.

**Comment by queicherius** [comment]
That's actually a really cool idea. Weapon+Accessories are cool on their own, is Armor also interesting?

**Comment by rediche** [comment]
Armor could be cool too. I think with armor it would be cool both with individual pieces between the game modes but also for weights.

Like being able to see PvE, WvW and PvP legendary sets in the game. And also see Heavy, Medium and Light sets in the game. 

Individual pieces might be hard to compare since PvE has one entire set where WvW has both T2 and T3 armor that can be legendary.

**Comment by queicherius** [comment]
Closing this, for a few reasons:

- We already show which legendaries are the most popular (in the [unlock statistics](https://gw2efficiency.com/account/unlock-statistics?filter.key=skins&filter.rarity=7)), which was the main reason why I thought this was cool
- It would make the job to calculate the unlock / playerbase statistics run quite a bit slower, because we'd have to process each account to pull all items out, and then sum the ones we are interested in. Right now, we just do a single loop over every unlock, which is already a pre-generated ID list + a single loop over the list of characters.
- It may leak data about our users that I am not entirely comfortable with, because I am not deep enough in the topic of legendary flipping
