### ISSUE TITLE
Tradingpost Overview: Link to GW2BLTC

### ISSUE THREAD

**Issue by scy** [gw2efficiency/issues#1345]
I love being able to look at a GW2Spidy chart for tracked items on the tradingpost overview page, but there's one thing missing from these graphs: The amount of sells/buys. An awesome flip profit or ROI will be worth nothing if nobody sells me that item, or worse, nobody's going to buy my stock.

As far as I can see, the GW2Spidy graphs don't provide that information. However, GW2BLTC does, via the vertical lines in the third chart:

![image](https://user-images.githubusercontent.com/28629/89703430-dace9380-d94a-11ea-9f4b-ef6a7ee8951f.png)

It would be awesome if, for each tracked item, there were be a button that simply linked to that item's GW2BLTC page, i.e. `https://www.gw2bltc.com/en/item/{item_id}`. Probably next to those for "buy stock", "show graph" and "delete"?

This could probably also be easily done in a browser extension, so if you don't think you'll be able to implement this for the foreseeable future, please let me know; I might go that route instead.

Thanks for your time and for GW2Efficiency!

**Comment by queicherius** [comment]
> The amount of sells/buys

I was always a bit careful with that, because the API actually gives no way to calculate this accurately. What BLTC does is just calculate the difference between their crawling points, which includes delisting and drops data that happened in the interval (so if an item is listed and sold in between their crawling points, its not picked up). Something to be aware of.

> This could probably also be easily done in a browser extension, so if you don't think you'll be able to implement this for the foreseeable future, please let me know; I might go that route instead.

This sounds like the plan for you :) I am not really planning to add this feature myself.

> Thanks for your time and for GW2Efficiency!

Thanks for using it!
