### ISSUE TITLE
Gemstore Account Upgrades & Account Value

### ISSUE THREAD

**Issue by MaxG46** [gw2efficiency/issues#1379]
The "Gemstore Account Upgrades" site is only available via the entry in Account -> Overview, I could not find it anywhere else.

The "Catmander's Compendium" is not included in this list. As I only own this one and not the "normal" one I am not sure if its value is included in the Account Value.

I think the "Living World Season X Complete Pack"s and "The Icebrood Saga Complete Pack" (or their single entries) should also be included in this list, and count towards the Account Value, maybe the Expansions too.

**Comment by queicherius** [comment]
That is intended, because the navigation is being a bit crammed

The catmanders compendium and living world packs are not in the API as far as I can tell.

The expansions won't count because it's quite hard to put a gemstore cost on them, since they are out-of-gemstore only purchases, and the price differs pretty dramatically based on offers and currency
