### ISSUE TITLE
Account Overview Not Updating

### ISSUE THREAD

**Issue by MoFunk37** [gw2efficiency/issues#1385]
My Account Overview graph shows November 24th as the latest date and won't show me any information past that date.

**Comment by queicherius** [comment]
Hey there, it's likely that is because you changed your in-game account name.

When changing your account name, as the first step please delete your old API key and create a fresh one. You should now be able to see your new crawling points, but not your old ones anymore. As the second step, please write support@gw2efficiency.com with your old and new account name to migrate all the old crawled data to the new account name.

**Comment by MoFunk37** [comment]
My in game account name has been the same since day one. MoFunk.3417

**Comment by queicherius** [comment]
It looks like you created your API key and it's working now 👍 
Maybe the API flagged your old one as invalid in error (happens sometimes).
