### ISSUE TITLE
Graph scale bar handles and range disappear

### ISSUE THREAD

**Issue by ralesk** [gw2efficiency/issues#1388]
If you drag the scale bar to make the X axis more squished (eg. in the Statistics part of the site), and while dragging, the mouse cursor leaves the graph widget, the range and handles will disappear and cannot be recovered without refreshing the page.  If you don't release the mouse button and return inside the graph area, it will reappear.

Browser: Firefox

**Comment by ralesk** [comment]
I was messing around with the sliders and can add to this that the slider assembly blinks out of existence sometimes even while inside the navigator bar, so there might be something else going on than leaving the graph in general.

**Comment by queicherius** [comment]
I had a play with this when it was first reported, and again now, and it looks like this is an issue with the charting library itself. I don't think the deep dive into their code will be worth fixing this bug, since you can get the slider by by clicking and dragging inside the chart area (or on page refresh)
