### ISSUE TITLE
Add option for legendary shard conversion to crafting gen 2 two-handed legendaries

### ISSUE THREAD

**Issue by Jazzyforcefield** [gw2efficiency/issues#1398]
As you may or may not know converting off-hand or one-handed weapon shards to two-handed shards is cheaper gold-wise by a large margin. Although it may cost a bit more map currency for the shards, the gold saved is very impactful for many players. As a result, an option for two-handed legendary crafting seems like a good idea to me.

A rough design for this would be to get the price of the cheapest Mystic Curio material and an off-hand or one-handed shard to purchase.
The system would then calculate that the user should craft X-many Enormous Chest of Legendary Shards depending on whether the price of crafting 100 shards vs the amount of shards they need to convert is favorable.
The system would tell the user that he/she needs to craft X-many of the off-hand/one-handed shards to convert to Enormous Chest of Legendary Shards in the Mystic forge.
Additionally, any remaining shards should be crafted the original method if the price of crafting the remainder is less than crafting an additional 100 shards to convert.

This may be applied to some of the 1-handed weapons as well.

Source: https://wiki.guildwars2.com/wiki/Enormous_Chest_of_Legendary_Shards

**Comment by queicherius** [comment]
This feature has been requested a few times, but is currently out of scope of what we want to do. The reason is both additional complexity in our recipe system as well as potential confusion for new users ("can I only get these shards from these chests?").

We recommend acquiring the shards using your preferred method first, and then using the calculator (which will mark the shards as owned materials)

**Comment by Jazzyforcefield** [comment]
Thank you for the details
