### ISSUE TITLE
Account with old API key crawling very often

### ISSUE THREAD

**Issue by Torphage** [gw2efficiency/issues#1432]
I recently changed my display name and for about two weeks I didn't merge the old and new gw2efficiency data, as I didn't see the problem at first.
This is the result during that time when an old API key. (Migrated account yesterday, works fine now)

I'm not sure if this is intentional behavior or not, but it looks rather demanding on the server side. Most of the statistic crawling were done in intervals of 1h, some as often as every 5min. I would expect it to stay at every 12h since I only have a copper tier supporter status.

![account-overview-graph](https://user-images.githubusercontent.com/17831168/119371823-04c52c80-bcb7-11eb-88f3-650855234759.png)

If this is not intentional, here are some observations I made during this time period that might help find the cause.
* The account graph was updated even on the old API. However, the graph was incorrect since it always stayed around 6.25-6.5k. Things like material storage, time machine (most of the time) still worked with the old API key.
* Unless I'm mistaken the account value number above the graph did were not in sync with the graph, as the number above the graph seems to update correctly. This was the reason I noticed something was wrong. I can't go back to confirm this since the graph was updated when the accounts were migrated.
* The time machine saved snapshots every 5 minutes, but most of these snapshots had no difference. A could only be seen when comparing two snapshots abour 2h apart, even though I only have a copper tier supporter status.

Additionally, it was only 3 days ago that I started adding new API keys to gw2efficiency, so this is not the cause.

**Comment by queicherius** [comment]
Hey :) Thanks for the issue, I appreciate you taking the time. 

The behavior you are seeing is likely because someone that *does* have a higher tier supporter status added your API key to their account (to be honest, it might even have been me if I migrated your account to make sure it worked). Platinum tier supporters get their account crawled every hour.

For future readers: Supporters get their status applied for all API keys on the account, so sharing with friends & family is possible. We generally encourage you to purchase your own, but we have no policy on disallowing it if it's not excessive (aka your whole guild).

The 5-minute ones are likely from when the API did not respond in time and we retried (and then the API responded for the first attempt).

We monitor the server load of crawling accounts very regularly, and it all looks good on our end in that regard :)

**Comment by Torphage** [comment]
Hm.. The only one who could have had access to my old API key when it started would have been an arenanet employee, when they changed my display name.

Guessing they added it to check something and forgot to remove it. Now when I think about it they probably checked one of my character names, since the ticket was anonymous.
