### ISSUE TITLE
wrong link in recipes

### ISSUE THREAD

**Issue by TristisOris** [gw2efficiency/issues#1442]
![изображение](https://user-images.githubusercontent.com/1270117/122877512-5953da00-d33f-11eb-9c22-fc92c1a20c99.png)
![изображение](https://user-images.githubusercontent.com/1270117/122877527-5d7ff780-d33f-11eb-911e-f85c082de728.png)

probably, correct code [&AgHIMQEA] if not duplicate.

same with other tiger's things:
[&AgGXMgEA]
[&AgFTMgEA]
[&AgGPMQEA]
[&AgGaMgEA]
[&AgFcMQEA]
[&AgGsMgEA]
[&AgFuMwEA]
[&AgF7MgEA]
[&AgHPMgEA]
[&AgFsMQEA]
[&AgEBMgEA]
[&AgFQMwEA]
[&AgGaMgEA]

**Comment by queicherius** [comment]
The issue there is that no wiki page for the recipe exists. The chat code you posted (`[&AgHIMQEA]`) is for the resulting item, not the recipe. The recipe item might only exist in the API and not in-game, since it looks like they get unlocked via https://wiki.guildwars2.com/wiki/Cymbel%27s_Baby_Book_Notes. So potentially this just gives you the recipe and immediately applies it.

In any case, I don't think this is something we can fix.
