### ISSUE TITLE
Add bulk recipe for Amalgamated Gemstones

### ISSUE THREAD

**Issue by Sollunad** [gw2efficiency/issues#1457]
Currently the bulk recipe is cheaper but the crafting calculator only shows the single recipe.

Recipe comparison (not factoring in chances at getting extra gemstones):

[Single recipe](https://wiki.guildwars2.com/index.php?title=Special:RunQuery/Base_ingredients_query&Base_ingredients%5Bitem%5D=Amalgamated%20Gemstone%2FRecipes&Base_ingredients%5Bid%5D=6806311&Base_ingredients%5Bdiscipline%5D=Mystic+forge&Base_ingredients%5Bquantity%5D=1&_run) is currently at around 67s per gemstone.

[Bulk recipe](https://wiki.guildwars2.com/index.php?title=Special:RunQuery/Base_ingredients_query&Base_ingredients%5Bitem%5D=Amalgamated%20Gemstone%2FRecipes&Base_ingredients%5Bid%5D=6806336&Base_ingredients%5Bdiscipline%5D=Mystic+forge&Base_ingredients%5Bquantity%5D=10&_run) is currently at around 56s per gemstone.

**Comment by queicherius** [comment]
This is currently intended, because else the calculator does not handle the cases well where you do not need the full 10 stones (e.g. Crystalline Ingots or the Commander's Dragon Slayer Weapons). It would cause it to craft 10 stones no matter what, and that would break a lot of the price calculations.
