### ISSUE TITLE
Incorrect Crafting Calculations for Food Salvaging

### ISSUE THREAD

**Issue by Falgar** [gw2efficiency/issues#1460]
When crafting Exquisite Extract of Nourishments, the crafting calculator does not take into account the excess "rarer" salvage results of some foods properly. While salvaging items from ratings 75-125 and 225-275, it does properly account for how many food items are needed to obtain sufficient quantities of the Fine and Masterwork Extracts, respectively; however, as the those 75-125 items also produce Masterwork Extracts and the 225-275 items produce Rare Extracts, the calculator does not reduce the required number of the higher rating foods to account for this. When crafting large quantities, this can cause significant overcrafting.

**Comment by queicherius** [comment]
I am actually not super up-to-date on how the salvaging works. Is there a list anywhere of items you receive back and expected quantities? I think i pulled the current ones from the wiki, but I might have missed the additional results

**Comment by Falgar** [comment]
The page for the portable composter has a chart and lists all the currently known exceptions to the expected results:
https://wiki.guildwars2.com/wiki/Portable_Composter
For the vast majority of food items, they only salvage into one extract, but for these in-between ranges, they have a 1/3 chance of dropping two extracts of the lower tier.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.

- We don't support a subrecipes having output for 2 or more higher level recipes
- There are a lot of inconsistencies to this pattern, some of which are not on the wiki (e.g. Sushi) so that would require too much manual testing & maintenance
