### ISSUE TITLE
Crafting Steps Order Options

### ISSUE THREAD

**Issue by Potawto** [gw2efficiency/issues#1526]
I would love options to change the order of the crafting steps in the crafting calculator. Sometimes they are just all over the place with similar steps spread all over the list.

I don't know what sort of system would be easiest or best, but even something as relatively simple as being able to manually drag-reorder the steps would be immensely helpful.

This came up for me when I was crafting items for Provisioner Tokens, and I had a crafting calculator bookmark that I used every 4 days. I would have loved to have a different order in the steps, to craft all elder weapon pieces together or all inscriptions together, for example.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.

This would be fairly complicated, because a lot of the crafting steps depend on the steps that happen before them so optimizing that requires those dependencies to stay intact.
