### ISSUE TITLE
Better check for item progression when crafting gen 2+ legendaries

### ISSUE THREAD

**Issue by Azania** [gw2efficiency/issues#1624]
Basically there are several problems I am running into;

1) I keep getting the following message no matter what, whther own materials or not, regardless of howmany Philosophers stones I have;

"Some sub-components of this recipe are included in a greater amount than required, because their recipes do not allow for the exact amount needed:
Philosopher's Stone (6 needed, 10 included)"

The last line even repeats for each leggy weapon I put in the calculator.

2) Steps somehow seem to place buying the amount of philosophers stones below any steps that actually use em, so wrong order.

3) Collection precursors are displaying no required materials in case of second crafting. Which is possible with the four gen2 collection weapons. 

Like I want to make a second Astralaria, problem is that the precursor The Mechanism is listed as earned from an achievement? When I put it in the calculator separately it lists the The Apparatus as already earned.. which I do need to craft as well. When I add Apparatus separately it somehow makes The Mechanism entry showing the mats needed for The Apparatus, making it double the materials.. When adding in The Device the materials needed for that one is then trippled. (from the device, from apparatus, from mechanish to apparatus and the device again). It seems impossible to get proper materials listed.

Hope it helps, 

~ Sarah

**Comment by queicherius** [comment]
> 1) I keep getting the following message no matter what, whther own materials or not, regardless of howmany Philosophers stones I have;

This is intended, the recipe uses 6 Philosophers but you can only buy them in bulks of 10, so the calculator is letting you know that you might be buying more than you need. (This also happens for other recipes where you can only craft/buy ingredients in bulk).

> 2) Steps somehow seem to place buying the amount of philosophers stones below any steps that actually use em, so wrong order.

Good find, it looks like this is because we pull the Mystic Clovers step into the front but not what it depends on. Added to #1593.

> 3) Collection precursors are displaying no required materials in case of second crafting. Which is possible with the four gen2 collection weapons.

I ran into this before, and if I remember correctly this is because the API doesnt give us the data if you're done with the collection or on the very last step before crafting it. Gonna have to loop deeper into it tho.

**Comment by Azania** [comment]
> > 1. I keep getting the following message no matter what, whther own materials or not, regardless of howmany Philosophers stones I have;
> 
> This is intended, the recipe uses 6 Philosophers but you can only buy them in bulks of 10, so the calculator is letting you know that you might be buying more than you need. (This also happens for other recipes where you can only craft/buy ingredients in bulk).

Should it then check the amount of Philosophers stone the player has then? It doesn't seem to do that at all. It always sayd you need 6 no matter what.

 
> > 3. Collection precursors are displaying no required materials in case of second crafting. Which is possible with the four gen2 collection weapons.
> 
> I ran into this before, and if I remember correctly this is because the API doesnt give us the data if you're done with the collection or on the very last step before crafting it. Gonna have to loop deeper into it tho.

Shouldn't it check whether the player has the item instead? Rather than the achievement? In the end they have to crafted and being an item before being salvaged into another item? The biggest issues are the weapons. Not the items from the box since you can just buy the box later for some karma. The achievements should not be relevant to check for whether there is the (spirit of) xxxxx weapon. Especially the precursor should be checked as an item. Is that possible or is it taking from the API hard as an achievement? That would not make much sense to me.

**Comment by queicherius** [comment]
> Should it then check the amount of Philosophers stone the player has then? It doesn't seem to do that at all. It always sayd you need 6 no matter what.

The warning is not about the stones the player has, but about the ingredients the recipe says it requires. This is a better example:

https://gw2efficiency.com/crafting/calculator/a~0!b~1!c~0!d~1-43451

It warns because the tree shows you need 5 superior stones, when you only need 1, because you can only craft them in stacks of 5.

We don't take player items into account at this step.

> Shouldn't it check whether the player has the item instead? Rather than the achievement? [...]

Sure, there's probably better ways to handle this, but they might take extra manual work etc (like what you suggested of looking into items would require us to manually specify this for the recipes). If you already have the exact item the recipe requires it should mark it as completed already. Gonna have to loop deeper into it.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.

If you are crafting the legendary for the second time, you can type in the precursor into the calculator.
