### ISSUE TITLE
account bound recipes and recipe containers not properly inheriting value from containers/contents.

### ISSUE THREAD

**Issue by Prezombie** [gw2efficiency/issues#1639]
This is most impactful in the core ascended recipes so that's where my example will be. 

"Recipe: Zojja's Visor" can only be acquired by explicitly selecting it from the container "Recipe: Ascended Heavy Helm", which can only be earned as a random fractal drop, or purchased.

Like ascended gear that can randomly drop, value appears to be set at the cheapest non-random way to acquire the item, correct?

Therefore, all core ascended recipes should be valued at the 3g+5laurel cost that the vendors require.

Lots of "no value" recipes that are purchased with Karma, which has a calculated value.

There's a big pile of HOT and POF recipe containers that are account bound, but the contained recipes inside are on the trading post. Their value should be at LEAST the cheapest choice, if not be the best choice, instead of their current no-value.

**Comment by queicherius** [comment]
> Like ascended gear that can randomly drop, value appears to be set at the cheapest non-random way to acquire the item, correct?

That is correct for _equipable_ ascended items because they have significant cost attached to them when crafted.

> Therefore, all core ascended recipes should be valued at the 3g+5laurel cost that the vendors require.

Not going to be implementing this at any point. Containers are not in the API, so we would have to manually maintain this mapping, and this would be super low impact on the account value in the grand scheme of things.

> Lots of "no value" recipes that are purchased with Karma, which has a calculated value.

We don't currently value anything bought with karma, because the value of karma is not defined. See [here](https://github.com/gw2efficiency/issues/blob/master/docs/account-value.md#wallet)

> There's a big pile of HOT and POF recipe containers that are account bound, but the contained recipes inside are on the trading post. Their value should be at LEAST the cheapest choice, if not be the best choice, instead of their current no-value.

Same thing, containers not in the API, basically 0 impact.
