### ISSUE TITLE
What actually counts toward account value?

### ISSUE THREAD

**Issue by Ahrle** [gw2efficiency/issues#1645]
For instance,

Frost Dye kit says:
Gem store price: 125 gems
Value: 38g 10s 00c 

Item Booster:
Gem store price: 100 gems
Value: no data

Kralkatorrik Dye Kit:
Gem Store price: no data
Value: no data

Shouldn't Item Booster add value equivalent to 100 gems, and Kralkatorrik dye kit to 125 gems (historical gemstore price according to wiki)?

**Comment by queicherius** [comment]
You can find our definition of account value [here](https://github.com/gw2efficiency/issues/blob/master/docs/account-value.md#account-value) and specifically the section about gemstore items [here](https://github.com/gw2efficiency/issues/blob/master/docs/account-value.md#gemstore-items).

Boosters (and a bunch of other objectively worthless items from dailies) are not assigned a value.

The Kralkatorrik Dye Kit does not have any gemstore data yet, since this is something we do manually and the item has not been part of that process yet.
