### ISSUE TITLE
Recipes with subrecipes that have a output > 1 may be wrong

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#166]
- Potent Superior Sharpening Stone (should be 1x Superior Sharpening Stone, instead of 5x)
- Rare Veggie Pizza (should be 1x Super Veggie Pizza, instead of 2x)
- Cosmic Mechanism (should be 10x Meteorite Ingots, instead of 25x)

**Comment by queicherius** [comment]
This was never technically a bug, but it now shows a warning when it happens.

**Comment by DavSalli** [comment]
Have to reopen this, since the recipe for Potent Superior Sharpening Stone is still wrong, but it shows no warning whatsoever (except for amounts not divisible by 5, but with other amounts such as 5, 10 etc. its also counting wrong)
![FireShot Capture 097 - Potent Superior Sharpening Stone - Crafting - Calculator - gw2efficie_ - gw2efficiency com](https://user-images.githubusercontent.com/75695169/173226924-e9699f6d-0595-4c49-8156-e1a3aae3ab20.jpg)
![FireShot Capture 094 - Potent Superior Sharpening Stone - Crafting - Calculator - gw2efficie_ - gw2efficiency com](https://user-images.githubusercontent.com/75695169/173226925-36030f97-9287-4987-a8dd-5d357ab3ec7a.jpg)
![FireShot Capture 095 - Potent Superior Sharpening Stone - Crafting - Calculator - gw2efficie_ - gw2efficiency com](https://user-images.githubusercontent.com/75695169/173226926-70a40bad-9159-4c60-94fd-40aa3c484f17.jpg)
![FireShot Capture 096 - Potent Superior Sharpening Stone - Crafting - Calculator - gw2efficie_ - gw2efficiency com](https://user-images.githubusercontent.com/75695169/173226927-09299612-a725-4e7b-88d7-1c5730473366.jpg)
.
