### ISSUE TITLE
[Request] Show stats on how many people in the community have which specific legendary items

### ISSUE THREAD

**Issue by Mendas88** [gw2efficiency/issues#1690]
I'm interested in learning how many people have crafted legendary runes and sigils, but more broadly, I think it would also be interesting to see what percentage of the community have crafted which legendary items. See which is the most popular weapon, which is the least etc.
Given the API lets you see what's inside inventories, I feel like this is achievable? 
Thank you :)

**Comment by queicherius** [comment]
For legendary skins this already exists: https://gw2efficiency.com/account/unlock-statistics?filter.key=skins&filter.rarity=7
Runes and sigils are tracked here: https://github.com/gw2efficiency/issues/issues/1555

For generic items I dont think we're ever going to do it, because it would be too expensive.
