### ISSUE TITLE
Account search returns items that contain the search term in their description.

### ISSUE THREAD

**Issue by SeparGW2** [gw2efficiency/issues#1706]
When searching for Philosopher's Stone the results included:  Agonized Essence, Bolt, Sunrise, Twilight, and Mystic Clover.  Each of these have 'Philosopher's Stone' somewhere in their description.
Would it be possible to add another drop-down to (by default) restrict the search to the title in the description and (optionally) search the entire description ?

![Philosopher's Stone](https://github.com/gw2efficiency/issues/assets/31021448/c4cb5ce6-8ab4-42f4-b499-ecc969cf2d4e)

**Comment by queicherius** [comment]
This is intended and how all the search boxes work on the page, because it mirrors how the in-game search works (e.g. searching `o o` to find all `Consume to open` descriptions). I would recommend using the `Type` filter instead if you want to only filter those (in this example, the "Trophy" option).

**Comment by SeparGW2** [comment]
Thanks for the response.  Will check out the 'Type' filter

    On Friday, September 8, 2023 at 10:37:27 PM EDT, David Reess ***@***.***> wrote:  
 
 


This is intended and how all the search boxes work on the page, because it mirrors how the in-game search works (e.g. searching o o to find all Consume to open descriptions). I would recommend using the Type filter instead if you want to only filter those (in this example, the "Trophy" option).
