### ISSUE TITLE
Add stats for total infusions and enrichments owned and missing Arcane Flow Infusion to cosmetic auras

### ISSUE THREAD

**Issue by Linkaaaaa** [gw2efficiency/issues#1748]
Possibilities:

- Total stat infusions (wvw included)
- Total cosmetic infusions
- Total enrichments
- Total cosmetic enrichments

Cosmetic Auras statistics are missing the [Arcane Flow Infusion](https://wiki.guildwars2.com/wiki/Arcane_Flow_Infusion) from the Wizard Vault

**Comment by queicherius** [comment]
I'm unsure if those stats are interesting - @Ecmelt thoughts?

We should add the aura data.

**Comment by Ecmelt** [comment]
We could merge them under another name since we already have cosmetic ones, we could have a non-cosmetic infusion/enrichment total.

So this is different because it wouldn't include cosmetic +5 +9 infusions in it. But yeah, i think this is more interesting at least.

End result would be:

Cosmetic Auras, which already include enrichments, individual cosmetic aura stats and a non-cosmetic aura stat (it is no longer an aura so probably better naming needed) without individual stats.

**Comment by Ecmelt** [comment]
At the end decided on adding a "Stat Infusions" statistic that counts all +5 +4. Arcane flow was already added in the previous update.
