### ISSUE TITLE
Generation 3 Variants are not correctly tracked in the calculator

### ISSUE THREAD

**Issue by Aguileitus** [gw2efficiency/issues#1752]
Take for example the Zhaitan's Insight Skin
https://gw2efficiency.com/crafting/calculator/a~0!b~0!c~0!d~1-98120

![image](https://github.com/gw2efficiency/issues/assets/14335637/88f204bd-ff37-4e5d-8daf-f5c3b3d6bae7)

I have already acquired the items from step 1 to step 4 but they still appear in the Crafting Steps

![image](https://github.com/gw2efficiency/issues/assets/14335637/996c9f43-bc3f-4c5c-9c69-00b96d20d4b8)

I think the recipe is skipping one step (combine all the Scale Splinters) and it's not correctly tacking the achievement.
This is valid for any other variant.

**Comment by queicherius** [comment]
Ah yeah, the recipe for that is wrong on our end. It looks like what you described - the step for combining into the https://wiki.guildwars2.com/wiki/Scale_Fragment_of_Zhaitan is missing and the https://wiki.guildwars2.com/wiki/Purified_Scale_Fragment_of_Zhaitan is missing as well.

Current tree:

- Zhaitan's Insight Skin
  - Fragment of Prismatic Shadows
  - Scale Splinter of Zhaitan
  - Scale Splinter of Zhaitan
  - Scale Splinter of Zhaitan 
  - Scale Splinter of Zhaitan 
  - Uncharged Fragment of Prismatic Shadows

Correct tree:

- Zhaitan's Insight Skin
  - Fragment of Prismatic Shadows
    - Uncharged Fragment of Prismatic Shadows
  - Purified Scale Fragment of Zhaitan
	  - Scale Fragment of Zhaitan
		  - Scale Splinter of Zhaitan
		  - Scale Splinter of Zhaitan
		  - Scale Splinter of Zhaitan 
		  - Scale Splinter of Zhaitan

**Comment by Aguileitus** [comment]
Thanks!
Don't forget to fix the tree for all the other variants as well :)

**Comment by JoeMylinn** [comment]
There are still issues with the current recipe. First, the original Issue persists, and the crafting isn't tracking the achievement for progress.

Furthermore, the new tree introduces a new issue. The Skin's can be bought directly with the Fragments, and shouldn't require the Purified Scale Fragment.

Current behaviour:
Fragment(s) of Prismatic Shadows owned, but crafting calculator still requires crafting of Purfied Scale Fragment of Zhaitan.
![image](https://github.com/user-attachments/assets/b5248f3c-5dc9-492e-aaf9-0311e9ebf77b)
![image](https://github.com/user-attachments/assets/03480ca3-5c52-43e3-aa40-0751b1141a65)

Expected behaviour:
Skins Should be craftable just with the Fragements.

I believe the correct tree would be:
- Zhaitan's Insight Skin
  - Fragment of Prismatic Shadows
    - Uncharged Fragment of Prismatic Shadows
       - Purified Scale Fragment of Zhaitan
         - Scale Fragment of Zhaitan
            - Scale Splinter of Zhaitan
            - Scale Splinter of Zhaitan
            - Scale Splinter of Zhaitan
            - Scale Splinter of Zhaitan

Could add more steps from the achievement too, but don't think that's necessary, since they don't introduce any cost.
