### ISSUE TITLE
Kralkatite Ingot wrong recipe

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#1802]
![image](https://github.com/gw2efficiency/issues/assets/5689996/eb5431b0-1ecd-4a68-a567-7ecfb437d68d)

![image](https://github.com/gw2efficiency/issues/assets/5689996/4a9957bc-6f38-49a4-933a-04606042394d)

**Comment by Ecmelt** [comment]
![image](https://github.com/user-attachments/assets/ddbddcf8-0fea-44a2-890f-92776df040f2)

The recipe is correct. It shows 25 because cheapest recipe we calculate for Kralkatite Ore outputs 25 ore (vendor purchase that is not daily limited).

It'll stay 25 if you try to craft 2 ingots (since 20 < 25) and jump to 50 at 3 ingots ( since 30 > 25 ). It is just how the calculations work right now.
