### ISSUE TITLE
Feature suggestion: guild log err logging

### ISSUE THREAD

**Issue by gartkb** [gw2efficiency/issues#1809]
At the moment the in game interface is horrific for managing a guild. Things that would be great to separate and track, roster changes, food donations, treasury in/out

**Comment by queicherius** [comment]
This is not possible to implement in a way that I would be happy with in the current version of the official API.

The API 
- is extremely slow, to the point of timing out all the time
- only returns the last XXX entries (I would love to check how many, but I cant get my guild log to load due to timing out), so wed have to re-fetch that on a timer and save it for ALL guilds. it also means as an audit log it's useless, because someone can spam XXX+1 entries and remove the nefarious entries.

After consideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
