### ISSUE TITLE
Character Image Display 

### ISSUE THREAD

**Issue by S1mul8r** [gw2efficiency/issues#202]
In the character overview section can you make it so we can add pictures of our characters.

**Comment by queicherius** [comment]
So originally the idea there was to include the rendered character avatars from the API. Since that is not happening anytime soon, I want to rework that page anyway to show some more useful information than it does right now.

I am against people uploading their own pictures because then there would be overhead again. Whenever people can upload stuff (**especially pictures**), there has to be a way for users to edit & delete, monitoring of what the users to, report systems, moderation systems etc etc. Else people **will** abuse the system.

---

I will close this because there is nothing for me to do here (the rework is in another issue), but feel free to keep the conversation going!
