### ISSUE TITLE
Assign materials to the most expensive recipe

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#225]
> Lets say we need one iron and one steel ingot. We have 3 iron ore. Right now the ore is assinged to whatever is needed first. But crafting iron and buying steel costs 12s while the other way around is only 7s16c

**Comment by queicherius** [comment]
@rikkuness This could also be interesting for you, if you like algorithmic things. 😄

**Comment by rikkuness** [comment]
You got it! Once I've nailed the other one 👍

**Comment by Systho** [comment]
I'd like to help on this, can you point me towards the relevant module / spec  ?

**Comment by queicherius** [comment]
The code where this change would need to be made can be found here: https://github.com/gw2efficiency/recipe-calculation

I have not written any specs/tests for it yet, so feel free to start with that! 👍

**Comment by Systho** [comment]
I've been thinking about a "perfect" algorithm for this problem but it's harder than it looks.

I can quite easily assign materials to the most expensive components first.

If two components share a common dependency but only one of the two can be entirely done without buying anything, then we will assign material to the most expensive even if it cannot be entirely done.

That problem is recursive.

Shall I start with the naive approach first and see how it goes ? Do you have an idea of an algorithm to make the "best" assignment ?

**Comment by queicherius** [comment]
> Shall I start with the naive approach first and see how it goes?

Honestly, I think even the naive approach would already be a massive improvement over what is currently used (go from top to bottom).

> Do you have an idea of an algorithm to make the "best" assignment?

Sadly not, I have not had the time to look into this at all yet.

Also thanks for tackling this! Appreciated.

**Comment by queicherius** [comment]
This is too complex for it's usefulness
