### ISSUE TITLE
Inventory slots list for characters

### ISSUE THREAD

**Issue by axyd** [gw2efficiency/issues#290]
First I just wanted to thank the gw2efficiency team for the wonderful work they put into the website. I got many of my guildies to use it, because it's awesome :P

The one thing that could be implemented is: adding a list with free/taken bag slots for all characters.
This would greatly help all of us hoarders, and mitigate the need to open all characters in new tabs, just to see who can mule some more useless impulse investments.

Thank you for your time and dedication.

**Comment by queicherius** [comment]
> First I just wanted to thank the gw2efficiency team for the wonderful work they put into the website. I got many of my guildies to use it, because it's awesome :P

Glad to hear that! :)

> The one thing that could be implemented is: adding a list with free/taken bag slots for all characters.
This would greatly help all of us hoarders, and mitigate the need to open all characters in new tabs, just to see who can mule some more useless impulse investments.

This is included in #31, which will probably come with the big rework of the whole UI coming up. Because it's a giant project, it's gonna be a while, but I am definitely planning it!
