### ISSUE TITLE
Show the infusion/upgrade value in the item tooltips

### ISSUE THREAD

**Issue by jcmoyer** [gw2efficiency/issues#599]
It would be cool if agony infusions in gear were used in determining character/account value.

Example:

![Example](http://i.imgur.com/gxuWxyY.png)

Something like this is worth around ~36 gold, which can quickly compound into a couple hundred gold when you sum up all the infusions in a character's gear.

**Comment by queicherius** [comment]
Infusions and upgrades are included in the account value [since 22. November 2016](https://github.com/gw2efficiency/issues/blob/master/CHANGELOG.md#v41930--2016-09-22). They don't show in the tooltip tho, good point. 

They should probably show as an extra value (e.g. `Value: 2s (incl. upgrades: 36g)`

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
