### ISSUE TITLE
Include value from expensive achievements

### ISSUE THREAD

**Issue by jcmoyer** [gw2efficiency/issues#639]
Some achievements have a massive gold value attached to them, to list a few:

- [Festive Imbiber](https://wiki.guildwars2.com/wiki/Community#Festive_Imbiber)
- [Patron](https://wiki.guildwars2.com/wiki/Contract_of_Patronage)
- [Ascended Recycling](https://wiki.guildwars2.com/wiki/Ascended_Recycling)

I don't think these are currently included in account value. Is it possible to include them?

**Comment by queicherius** [comment]
> Festive Imbiber

The gold value is attached to the reward item (Winter's Presence), else it would count twice

> Ascended Recycling

The gold value *should* be attached to the reward item (Fractal Reliquary), but I am not sure if that recipe is in the system. **Could you please double-check?**

> Patron

Now this is the only achievement I know of that does not "reward" you with an actual item that gets counted in the account value. I discussed [previously](https://www.reddit.com/r/gw2efficiency/comments/53z9l8/account_value_dropped_1k_after_spending_these_1k/) why I won't add this, but here is the gist of it:

- If I add the value of achievements, I have to require the `progression` permission for the account value to be generated.
- I have to force all keys to have the permission, else the values are not comparable with each other, since they stem from different data (with / without achievements)
- Currently about 1/3 of the keys do *not* have that permission, so I would have to throw out all of their data (which I am not going to do). This ratio may change for the better in the future, and then I'll rethink this. :)

**Comment by jcmoyer** [comment]
My bad, it does look like Winter's Presence and Fractal Reliquary both have the proper value attached to them. Personally I am in a weird spot where I've gotten Festive Imbiber, but I haven't finished the WP collection yet. gw2efficiency just shows a dip in account value where I've purchased the drinks and gotten countable nothing to show for it. It's a shame that nothing can be done about Patron, but it's understandable. Thanks for the response.

**Comment by queicherius** [comment]
Going to close this one out - 20% of users still are missing the permission for this to work (for some reason) and there has been only one achievement so far that would have a value.
