### ISSUE TITLE
Include currencies into the cost breakdown of the crafting calculator

### ISSUE THREAD

**Issue by queicherius** [gw2efficiency/issues#64]
It would be good to show karma, spirit shards and dungeon tokens at the cost breakdown at the top as well.

**Comment by dbenoy** [comment]
I wonder if I can ask to extend the scope of this issue like I described in #234 to include not just karma, spirit shards, and dungeon tokens, but anything that is account bound or otherwise unattainable with gold.

Like, for example, the Eternal Sands recipe calls for 250 Piles of Silky Sand, which can't be attained with gold, karma, spirit shards, or dungeon tokens. In essence it's another currency that one needs to grind for.

There are probably lots of other examples like this.

It would be super convenient and awesome if a little summary of this stuff can come up along with some tiny one-sentence blurbs on how each of them is acquired.

**Comment by queicherius** [comment]
> Like, for example, the Eternal Sands recipe calls for 250 Piles of Silky Sand, which can't be attained with gold, karma, spirit shards, or dungeon tokens. In essence it's another currency that one needs to grind for.

That's true, good point. All of this data would need to be hardcoded anyway, so it might as well be close to all "currencies" you can use in the game.

**Comment by dbenoy** [comment]
Ultimately there is little that distinguishes an in-game currency and an inventory item, with the sole exception of gold, because it can be used to interact with the Trading Post.

This can cause an interesting result when you try to resolve a price. For example, you may find that you have multiple alternative prices, like 10 badges of honor and 5 gold, or just 10 gold.

Perhaps if all the data gets fed in and you start to resolve it, your algorithms may spit out a long list of possible permutations of ways you can buy the item.

I guess that problem can be solved on the crafting page by changing it so instead of choosing 'Trading Post' vs. 'Crafting' you can select all the various ways of acquiring the item. For example, 'Trading Post', 'Vendor 3 gold', 'Vendor 2 gold, 10 badges of honor', 'Vendor 1500 karma', 'Crafting', and just try to choose sane defaults and allow the user to tweak at the output until they're satisfied with the ultimate cost that resolves from the tree.

Spaking of trees, I suppose this rabbit hole gets deeper. I wonder if you might be able to get routes of varying circuity. Like maybe if you buy it from a vendor using items you can craft, then you may end up altering the size of the crafting tree while you're making your selections.

What fun. Is this all open source? Maybe I might take a peek at what you have.

**Comment by dbenoy** [comment]
If you wanted to get truly hideous you could even throw in 'you can buy X of Y and you have an average chance of salvaging it' but then you'd need to know drop rates and that is probably information that doesn't publicly exist to any degree of reliability.

**Comment by queicherius** [comment]
> What fun. Is this all open source? Maybe I might take a peek at what you have.

Most stuff of the crafting calculator is online [here](https://github.com/gw2efficiency/recipe-nesting) and [here](https://github.com/gw2efficiency/recipe-calculation).

**Comment by wullxz** [comment]
Some currencies have a listing of stuff you could buy with them on their wiki page. You could parse those tables to add a price to some items. [Ascended Shards of Glory](https://wiki.guildwars2.com/wiki/Ascended_Shard_of_Glory) for example has a listing like that.

**Comment by queicherius** [comment]
@wullxz Yeah I want to add wiki parsing with #256 but its a massive amount of work

**Comment by queicherius** [comment]
Support for this tracked via https://github.com/gw2efficiency/issues/issues/1574 (and coming very soon), data updates will be another ticket.
