### ISSUE TITLE
Historical global statistics

### ISSUE THREAD

**Issue by risingashes** [gw2efficiency/issues#718]
![image](https://cloud.githubusercontent.com/assets/12869762/24479610/ceea27b4-152b-11e7-85f8-3996c1daff99.png)

Currently only current stats for global statistics are displayed (broken up by playtime), for certain statistics (gold, account value, etc) a historical trends graph would be very interesting.

I would suggest separating the data based on % of population and date, allowing the filtering out of % of population lines that are irrelevant to the player. (Alternatively the bucket to which the player belongs could be displayed by default along with the 'everybody' bucket, with other buckets able to to filtered in).

For the pure gold statistic this would allow us to see the inflationary pressure of gold generation over time, and the transfer of gold between different player segments (over the last year gold for the bottom 50% increased while the top 0.1% decreased, this could indicate that the daily gold rewards have....).

This would require the retention of global statistics on a daily basis, a rejiggering of the overview graph to include multiple lines again (almost certain the element has that functionality since it was used prior to the revamp), and a new page which is intuitively distinct from the statistics page so users know which dataset they're after (perhaps calling it trends and leaving personal statistics as statistics would do it, the only alternatives that jump to mind involve multiple words and are clunky).

**Comment by queicherius** [comment]
I already keep the statistics indefinitely, so this would be possible, but requires transformation into a different format which is not as computationally heavy to query. Definitely interesting idea for the future.

**Comment by queicherius** [comment]
I am closing this because while it is a pretty cool idea (and I might do a one-off calculation for that), it's not something I can reasonably generate/store at the moment. It's very computationally heavy (I'd have to go through something like 200m rows) and/or very storage heavy (and that's already becoming an issue).

Also while cool, I dont think the impact will be high enough to justify the complexity/time requirement (people would open the page, go "huh cool", and then come back in like half a year).
