### ISSUE TITLE
Missing recipe unlocks

### ISSUE THREAD

**Issue by vbonifaci** [gw2efficiency/issues#727]
Several recipe unlocks are not reported. This seems to occur more frequently with Ascended recipes and/or recipes obtained from special vendors (e.g. Dry Top).  

For example on my Mesmer, the following Artificer recipes are missing, among others: 
- Laranthir's Artifact
- Tonn's Artifact
- Wupwup Artifact
etc. On the other hand, a few other Ascended recipe unlocks are correctly reported.

**Comment by queicherius** [comment]
Could you send me your API key via email (admin@gw2efficiency.com)? Then I can check it against the API and file a bug there, if they are missing.

**Comment by queicherius** [comment]
Alright, so after looking through the API with your provided key I could find the described recipes. However, since recipes ingame moved from being character bound to account bound a while ago, they don't show up on all characters, only the character you unlocked it in (and they don't have the profession active atm, for example).

This is a bug, but it will also be fixed as soon as the new recipes page (#100) is done.

**Comment by vbonifaci** [comment]
Thanks, I get it now.

Best,
Vincenzo
Il 30/apr/2017 04:02 "David Reeß" <notifications@github.com> ha scritto:
