### ISSUE TITLE
Add "g/s/c" when copying gold values out of the website

### ISSUE THREAD

**Issue by ralesk** [gw2efficiency/issues#730]
I suppose it would be convenient if ![image](https://cloud.githubusercontent.com/assets/1564502/25742028/d30a4d78-318d-11e7-87ef-e305a0af5c63.png) copied to clipboard as `72g 95s 00c` instead of `72 95 00`.  This could be achieved with setting an alt text for the respective images, if I'm not mistaken.

Other currencies might benefit from a similar change as well.

**Comment by queicherius** [comment]
I tried something like this a while ago, and there were some issues with it. Mainly because the images of the money there are not actually images, but sprites, and when adding text inside the sprite container it would show up weirdly and copy with spaces like `72 g 95 s 00 c`

Ill see when I give this another look

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
