### ISSUE TITLE
Suggestion: GW2E integrations with GW2Armory

### ISSUE THREAD

**Issue by madou** [gw2efficiency/issues#745]
Hey !

A user brought up an interesting suggestion - getting gw2e statistics onto gw2a user pages. 

Now I have no intention in ever doing statistics as granular as efficiency has - but I have to admit it would be interesting getting some stats into the armory to link back to efficiency.

How I'm imagining it working is basically:

1) Creation of a "gw2e statistics" tab on a users page with a call-to-action to go register an account over at efficiency

2) Proxy data through my api for user statistics using the same token from gw2a to access their gw2e statistics data (e.g: https://api.gw2efficiency.com/tracking/personal?tracking_key=values.summary.value)

3) If data comes back from the api, display some basic statistics (account value, gold, etc) depending on what the gw2a user wants to show

4) Have a call-to-action that links back to efficiency to get a more detailed look at the stats

But it's all open for discussion, all assuming you'd even want this. What's your thoughts? 

If this doesn't really tickle your fancy I'd be keen to work something else out, I think collaborating on some cross site stuff would be pretty fun.

**Comment by queicherius** [comment]
So I just stumbled across this issue, which for some reason didn't get sent to my email or got filed under spam. My bad.

---

Let me just brain-dump the first things coming into my mind for this deal, which seems to be very much favoured in your direction in my opinion:

- Statistic creation/account value is the part of the website that it is most known for, and what most users come back for on a regular basis, so it's not in my best interest to show it on other pages
- Statistic creation is **by far** the most cost expensive part of the page. I could host everything *but* statistics on 5$/month (and I have in the past), with statistic generation I am at around 150$ a month, just because of the pure resource requirements for crawling all the accounts and saving the data in the long term
- It is also **by far** the most time intensive task to maintain for me, because of all the new API additions, changing values for items that are not in the API (e.g. gemstore items and similar) and general game updates

I hope you can see why I don't want the statistics to be displayed on a different page. Maybe if the deal would be "sweeter", I would be more inclined to think about it, but I can currently not think of a way to make it evener.

That said, I was, am, and will be up for collaboration, especially in the case of sharing code - as we already do with e.g. the item stat parsing or in the case of other pages with the API client. 

If you want to, feel free to hit me up on a more "real-time" platform, e.g. Discord (queicherius#0479) or Gitter if you want to discuss other options.
