### ISSUE TITLE
Small bug with AR display when using one-handed weapons

### ISSUE THREAD

**Issue by Wiella** [gw2efficiency/issues#746]
Game allows you to put just two one-handed weapons into two weapon sets to enable weapon-swap (put main-hand weapon into first set and off-hand weapon into second set) - in that case you have same weapons on both sets as main-hand and off-hand weapons are shared between sets if some of the weapons is missing.

Here is a screenshot for the case:
![image](https://cloud.githubusercontent.com/assets/26770339/26308139/a635d044-3f00-11e7-8854-784bd5672120.png)

The problem is displayed 145 AR. Each of the weapons I have there has +5 AR infusion so as the result I actually have 150 AR in-game since off-hand weapon from second set is shared to first set and vice-versa. But it seems that AR calculation algorithm doesn't take that into account and simply counts AR from the first (or second?) set weapons which is just one dagger with +5 AR in this case, so it seems that I'm missing another 5 AR to 150.

**Comment by Wiella** [comment]
Here is the actual in-game screenshot with the same gear and 150 AR displayed properly:
![image](https://cloud.githubusercontent.com/assets/26770339/26308330/6decc7aa-3f01-11e7-96b2-a108fea7e836.png)

**Comment by Wiella** [comment]
By the way, now I also noticed that stats calculation seem to suffer from the very same problem as well.

**Comment by queicherius** [comment]
Oh wow, this is an edge case I did not think of. Good catch!

**Comment by Systho** [comment]
Hi @queicherius ! I'd like to tackle this issue. 
I understand that the problem is probably in item-attributes/src/parseCharacter.js but according this function receives only a "flat" array of items.

I could not find any example of a character having two sets (partial or full) of weapons.

Would the item list look like `[...otherItems, weaponA1, weaponA2, weaponB1, weaponB2]` ? And this case look like `[...otherItems, weaponA1, weaponB2]` ?

is there a guarantee that the weapons are ordered by set ?

can I approach this issue like this ?

if there is one two handed weapon , then 0, one or more weapons : use the two handed weapon
if there is one single handed weapon, use its attributes
if there is one single handed then a two handed weapon, use the single handed
if there are two single weapons, combine their attributes (either in the same set or in two sets)
if there are two single weapons, then a two handed, combine the two single weapons
if there are three single weapons, combine the first two (and here is a bug again if there is one weapon in the first set and two in the second set, because we should use the first and last)
if there are four single weapons, combine the first two

I think that's the only way of only changing one lib, the other "cleaner" way would require changing the calling code which is a much bigger change

**Comment by queicherius** [comment]
I just checked the code. To my surprise, the part that calculates the AR is actually not in the public library but in the closed source frontend code. It's also very ugly and has some things unique to the internal implementation. Changing that would require some rewriting in both the library and the closed code, so it's probably best if I just fix it in the closed source for now (since its such a small thing).

Sorry for the confusion! I'll remove the tag. Thanks for the offer tho, appreciate it

**Comment by queicherius** [comment]
Fixed.
