### ISSUE TITLE
show count of historical vs currently obtainable achievement points

### ISSUE THREAD

**Issue by jacob-keller** [gw2efficiency/issues#766]
Would it be possible for the site to calculate our AP total excluding the historical achievements category? or show historical achievements total so we can figureout how much we've earned that cannot be earned by a new account?

**Comment by queicherius** [comment]
This is exactly what the "available" display shows you, and what you can see when you change "Show" to "Earnable":

![](http://i.imgur.com/JSnhwFR.png)

Is this not what you need?

**Comment by risingashes** [comment]
So @jacob-keller's use scenario would be if two friends were playing, one who had played from launch and the other who had started playing 1 month ago.

The friends have a bit of friendly banter where the newbie claims to only be behind because of historical and both wish to find out their achievable achievement score.

While your (@queicherius) suggestion gives them what they want, it's in a format that is the opposite of what most people are used to (lowest points wins).

@jacob-keller wants the screen to show him 15720/29171.

The points could display this way if the user selected the Earnable filter.

As to whether this should be done, meh. It seems fairly niche, and while it probably wouldn't put anyone off as knowing your current AP is no longer relevant if you're filtering to earnable (as you've already decided to AP hunt at that point and are no longer looking for generalist information) if might confuse someone somehow temporarily.

**Comment by jacob-keller** [comment]
Actually what I want (now, after studying the interface more clearly) is if
you click a major category like historical to show how much you've earned.
It already shows this if I click a category like auric basin, it shows how
many of that section and how much AP. However it doesn't provide a summary
for an entire category like historical or heart of Thorns

**Comment by queicherius** [comment]
Oh so you'd want basically this interface ![](http://i.imgur.com/tYH1Y1P.png) just for the "big groups"? Not sure where I'd even put that...

**Comment by jacob-keller** [comment]
Yes exactly that.

**Comment by risingashes** [comment]
If collapsing or expanding a big group instead displayed all relevant
achievements for that group, you could put the number at the top of the
display where it currently is.

If I'm looking at collections, I could see myself wanting to see all
collection achievements rather than just rare collections OR legendary
achievements. And then have the option to further drill down.

The downside would be it would add additional loading for people who are
specifically trying to get to the subgroup (a person specifically looking
for their remaining legendary collection achievements, who came to the site
for that alone). I'm not sure which group would have more members. The
ingame UI would probably serve those who wanted to drill down to specifics,
meaning the majority of people using out of game tools likely are browsing
semi-randomly, as a guess.

**Comment by queicherius** [comment]
Instead of adding an extra subpage, the major information (current/total AP and current/total achievements) are now just displayed in the navigation. I think that solves most use-cases. 

![](https://i.imgur.com/l2G14Jg.png)

**Comment by jacob-keller** [comment]
This is perfect! Exactly solves the usecase I had in mind, so I can easily
compare how many points I could earn :D
