### ISSUE TITLE
502 bad gateway https://api.gw2efficiency.com/user/status

### ISSUE THREAD

**Issue by FreezyExp** [gw2efficiency/issues#769]
Fetch API cannot load https://api.gw2efficiency.com/user/status. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://gw2efficiency.com' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by queicherius** [comment]
Hey there,

There are multiple reports of login issues. I currently can't look into or
fix the issue since I am 300 miles away from my PC. Earliest ETA for a fix
is Tuesday morning. Until then you might be able to use thr page without
logging in and just your API key.

Cheers,
David

**Comment by FreezyExp** [comment]
https://forum-en.guildwars2.com/forum/community/api/v2-commerce-delivery-temporarily-disabled

probable cause

**Comment by mewa** [comment]
Judging from the logs there is definitely an issue with CORS.
Though it could be related to what @FreezyExp has mentioned and CORS is just failing on error responses after the api fails to get data.

**Comment by queicherius** [comment]
Here is what happened, in case you were wondering:

1. We went on holiday :fire:
2. The commerce/delivery API got disabled
3. All backend crawling throws errors since they try to grab the contents, and my error wrapping didn't work as I thought it would
4. The error logs of these failures are persisted in one of the DBs (Redis) because that's what the library authors implemented even tho its stupid
5. The DB fell over from having 50 million keys
6. The internal API fell over because of no DB 😞 

Login and most other things should be fixed now, just fixing the account overview as we speak.
