### ISSUE TITLE
Sorting of Material Storage

### ISSUE THREAD

**Issue by maxOS1104** [gw2efficiency/issues#793]
If possible, it would be nice if the Material Storage tab would reflect the new sorting order of materials ingame :)

**Comment by queicherius** [comment]
The order of items is supplied by the official API, I added an issue there; https://github.com/arenanet/api-cdi/issues/556

Thanks for the report!

Since this is an API problem and will fix itself on gw2efficiency as soon as it's fixed there, without me having to update anything, I'll close this issue. 👍
