### ISSUE TITLE
Add "Masteries" in the "Account"-section. There you could see your locked and unlocked masteries/points and your currently available points

### ISSUE THREAD

**Issue by Skaldhor** [gw2efficiency/issues#811]

**Comment by queicherius** [comment]
- The mastery points can be managed via the "Achievements" section, since all of them are bound to achievements. There you can also filter by locked/unlocked/started and which one's (Tyria/Maguuma/PoF). ![](http://i.imgur.com/GkjNvWn.png)
- The masteries (imo) do not really give any benefit to have on the website, since there is a pretty clear panel for them ingame and you just click them once and are done.
