### ISSUE TITLE
Add "crafting price" & "crafting profit" columns to tradingpost listings

### ISSUE THREAD

**Issue by shrugal** [gw2efficiency/issues#818]
I use the TP and crafting sections to figure out what to craft (especially daily CDs), but right now those sites make it quite hard because the required info is split between those pages and there are no links between them. 

So I want to propose the following:

- Add the price and volume charts from the trading post section to the crafting page, for mats (shopping list) as well as produce. The same toggle icon as on the trading post listings would be perfect.
- Add a link from trading post listings to their respective crafting recipes.
- Add "Crafting price" and/or "Crafting profit" columns to trading post listings, similar to "Flip profit". Add dropdowns at the top to specify whether to use buy or sell offers for buying mats and selling the produce.

Those changes would make it much easier to figure out what to craft, when to buy mats, for how much, and what listing prices are reasonable for the produce given the recent market data.

**Comment by queicherius** [comment]
> Add the price and volume charts from the trading post section to the crafting page, for mats (shopping list) as well as produce. The same toggle icon as on the trading post listings would be perfect.

This is pretty hard.

> Add a link from trading post listings to their respective crafting recipes.

This is pretty easy.

> Add "Crafting price" and/or "Crafting profit" columns to trading post listings, similar to "Flip profit". Add dropdowns at the top to specify whether to use buy or sell offers for buying mats and selling the produce.

That is also pretty easy, the data is already there, just not displayed.

I'll definitely keep this in mind when I'm touching these pages again, thank you!

**Comment by shrugal** [comment]
> This is pretty hard.

If it's to labor intensive then maybe just add a link to a search for that item on the TP page. It's not quite as nice but should get the job done.

**Comment by Irubataru** [comment]
> If it's to labor intensive then maybe just add a link to a search for that item on the TP page. It's not quite as nice but should get the job done.

I would in general find it awesome if a link between an item and the TP page could be implemented throughout the tool. E.g. when I am browsing my bank on gw2efficiency and have an item I am contemplating selling, it would be practical if I could click the item (or a link somewhere), and directly go to the TP page displaying the TP trend of that item, instead of having to move over.

I think the TP tool is neat and handy, however I do not use it nearly as often as I should because searching it and finding the item I am looking for is both slow and a bit tedious. If I had a direct link from an item to the TP page, I would hopefully use that really useful tool more often.

Keep up the good work :smile:

**Comment by queicherius** [comment]
The cross-reference links now have their own ticket in #865

**Comment by queicherius** [comment]
I think I finally figured out where to put this one: https://i.imgur.com/6QI9c82.png

**Comment by queicherius** [comment]
This is now live. Sorry it took so long x_x
