### ISSUE TITLE
Why is there no War Gods Skins on the Site?

### ISSUE THREAD

**Issue by mirtisdyleris** [gw2efficiency/issues#837]
I cant see them in the Claim Tickets Tab...

its on the wiki doe..

**Comment by queicherius** [comment]
Good question, really weird behaviour. I'll see when I can find some time to take a look, because it seems to be catching all the other skins perfectly fine.

---

If anyone wants to take on this issue, the code is in [this repo](https://github.com/gw2efficiency/scraping) - ([source](https://github.com/gw2efficiency/scraping/blob/master/src/gw2wiki/claimTicketOffers.js), [tests](https://github.com/gw2efficiency/scraping/blob/master/tests/gw2wiki/claimTicketOffers.spec.js))

**Comment by mirtisdyleris** [comment]
would be nice. also when the new skins will come out it would be nice that it works fine.

**Comment by mirtisdyleris** [comment]
Also isnt showing the new Sand Skins

**Comment by queicherius** [comment]
This is now live. Thank you for your feedback. 😄
