### ISSUE TITLE
Feature Request: Buy/sell price selection for Wardrobe and Recipes pages

### ISSUE THREAD

**Issue by kazerniel** [gw2efficiency/issues#854]
This would be a minor, but handy addition. When trying to complete skin and recipe collections I don't need them _immediately_, so it would be nice if I could order them by buy price to get a more accurate picture of how much they would likely cost.

(As I see a similar feature is already implemented on the Dyes page.)

**Comment by queicherius** [comment]
This is a bit tricky, because the price shown there is not technically the **sell price**, it's the **value** ([here ](https://github.com/gw2efficiency/issues/blob/master/docs/account-value.md#item-value-1) is how that is getting calculated). I'd have to see if I even have the other prices available in the data blob I generate, I am not sure anymore.

**Comment by queicherius** [comment]
After reconsideration, this is not a feature that is worth the time investment for the gained value in my opinion, so I am going to close this ticket.
