### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by thoanny** [gw2efficiency/issues#962]
Hi !

First, great job! <3

How can I help you to translate some parts of GW2Efficiency in french?
What is the best way?

Thanks.

**Comment by queicherius** [comment]
> First, great job! <3

Thanks!

> How can I help you to translate some parts of GW2Efficiency in french?

Right now translations are closed because I am reworking the internal system (you may have noticed that all newer pages are not translated). Feel free to send me a mail to admin@gw2efficiency.com tho, then I can contact you when I am done :) Be warned that this is not a high priority at the moment.
