### ISSUE TITLE
Crafting calculator don't use data about achievements anymore.

### ISSUE THREAD

**Issue by malagus** [gw2efficiency/issues#966]
It's look like crafting calculator stop using data about completed parts of achievements. 
In my case crafting calculator show for example that i need to craft 250 x Basic Mithril Greatsword for  Basic Mithril Nightsword Requisition even if this step is already done. 
![zrzut ekranu z 2018-05-14 13-13-33](https://user-images.githubusercontent.com/12558492/39994408-8676edaa-5779-11e8-96cf-4bdd9f002f9b.png)
![zrzut ekranu z 2018-05-14 13-11-23](https://user-images.githubusercontent.com/12558492/39994411-89037f48-5779-11e8-8444-3da3d136b2e2.png)

**Comment by queicherius** [comment]
I was reworking the recipes a few days ago (before I went on holiday) to clean things up and removed some achievement bits because I thought "the calculator does not take these into consideration anyway". Turns out I added that it does take that into consideration since I added that nearly 2 years ago, and forgot about it. This damn page does more stuff than I remember.

It'll be fixed soon.
